In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# **데이터 업로드 및 함수 사용**

In [ ]:
import pandas as pd
import re
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
from sklearn.metrics import silhouette_score
from itertools import combinations
import numpy as np
import seaborn as sns
from sklearn.decomposition import PCA

data = pd.read_excel('/content/drive/MyDrive/위치/위치 최종과정_데이터 정리.xlsx', sheet_name = 'P_U 척도')

In [ ]:
data.head(4)

,U_id,P1,P2,P3,P4,P5,P6,P7,P8,P9,...,P19,P20,P21,P22,P23,P24,P25,P26,P27,P28
0,U1,4,3,4,2,5,2,3,5,5,...,2,2,1,2,4,3,4,4,3,4
1,U2,3,3,3,3,3,3,3,3,3,...,3,5,3,3,3,3,3,3,3,3
2,U3,4,2,5,4,4,2,1,2,5,...,4,4,5,2,4,3,3,3,2,4
3,U4,3,5,3,2,3,3,3,5,4,...,2,4,2,3,2,1,2,2,4,2

# **데이터 확인**

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 29 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   U_id    15 non-null     object
 1   P1      15 non-null     int64
 2   P2      15 non-null     int64
 3   P3      15 non-null     int64
 4   P4      15 non-null     int64
 5   P5      15 non-null     int64
 6   P6      15 non-null     int64
 7   P7      15 non-null     int64
 8   P8      15 non-null     int64
 9   P9      15 non-null     int64
 10  P10     15 non-null     int64
 11  P11     15 non-null     int64
 12  P12     15 non-null     int64
 13  P13     15 non-null     int64
 14  P14     15 non-null     int64
 15  P15     15 non-null     int64
 16  P16     15 non-null     int64
 17  P17     15 non-null     int64
 18  P18     15 non-null     int64
 19  P19     15 non-null     int64
 20  P20     15 non-null     int64
 21  P21     15 non-null     int64
 22  P22     15 non-null     int64
 23  P23     15 non-null     int64
 24  P24     15 non-null     int64
 25  P25     15 non-null     int64
 26  P26     15 non-null     int64
 27  P27     15 non-null     int64
 28  P28     15 non-null     int64
dtypes: int64(28), object(1)
memory usage: 3.5+ KB

In [ ]:
new_data = data.drop('U_id', axis=1)
new_data

,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10,...,P19,P20,P21,P22,P23,P24,P25,P26,P27,P28
0,4,3,4,2,5,2,3,5,5,3,...,2,2,1,2,4,3,4,4,3,4
1,3,3,3,3,3,3,3,3,3,3,...,3,5,3,3,3,3,3,3,3,3
2,4,2,5,4,4,2,1,2,5,1,...,4,4,5,2,4,3,3,3,2,4
3,3,5,3,2,3,3,3,5,4,1,...,2,4,2,3,2,1,2,2,4,2
4,3,4,2,2,3,4,3,4,5,2,...,2,4,2,3,3,2,2,2,2,2
5,3,4,3,3,5,5,4,5,5,3,...,4,3,5,3,5,3,5,5,5,5
6,4,4,3,3,4,4,3,4,4,3,...,4,5,4,3,3,3,4,4,4,4
7,3,3,4,2,4,2,4,2,4,4,...,4,3,4,2,4,2,3,2,2,4
8,2,5,4,2,4,5,2,4,5,3,...,3,5,2,2,4,2,4,3,3,4
9,1,3,2,2,4,3,2,2,4,2,...,2,4,2,2,2,2,2,2,2,2
10,1,2,3,4,4,4,5,4,4,2,...,3,3,2,2,3,2,4,4,5,4
11,4,4,3,2,4,3,2,2,3,2,...,3,3,2,1,4,2,4,5,4,3
12,5,3,3,5,5,3,3,5,3,4,...,2,5,3,3,2,4,3,2,3,3
13,4,5,2,2,3,4,5,4,4,2,...,2,3,3,4,3,2,4,2,5,4
14,2,3,4,4,4,4,2,4,4,4,...,3,1,4,2,4,3,4,4,3,4

## **kMeans 모델 적용**

In [ ]:
kmeans = KMeans(n_clusters=3, random_state=42)
clusters = kmeans.fit_predict(new_data)
# 클러스터링 결과를 DataFrame에 추가
data['Cluster'] = clusters

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

In [ ]:
data

,U_id,P1,P2,P3,P4,P5,P6,P7,P8,P9,...,P20,P21,P22,P23,P24,P25,P26,P27,P28,Cluster
0,U1,4,3,4,2,5,2,3,5,5,...,2,1,2,4,3,4,4,3,4,1
1,U2,3,3,3,3,3,3,3,3,3,...,5,3,3,3,3,3,3,3,3,1
2,U3,4,2,5,4,4,2,1,2,5,...,4,5,2,4,3,3,3,2,4,1
3,U4,3,5,3,2,3,3,3,5,4,...,4,2,3,2,1,2,2,4,2,0
4,U5,3,4,2,2,3,4,3,4,5,...,4,2,3,3,2,2,2,2,2,0
5,U6,3,4,3,3,5,5,4,5,5,...,3,5,3,5,3,5,5,5,5,2
6,U7,4,4,3,3,4,4,3,4,4,...,5,4,3,3,3,4,4,4,4,2
7,U8,3,3,4,2,4,2,4,2,4,...,3,4,2,4,2,3,2,2,4,1
8,U9,2,5,4,2,4,5,2,4,5,...,5,2,2,4,2,4,3,3,4,2
9,U10,1,3,2,2,4,3,2,2,4,...,4,2,2,2,2,2,2,2,2,0
10,U11,1,2,3,4,4,4,5,4,4,...,3,2,2,3,2,4,4,5,4,2
11,U12,4,4,3,2,4,3,2,2,3,...,3,2,1,4,2,4,5,4,3,2
12,U13,5,3,3,5,5,3,3,5,3,...,5,3,3,2,4,3,2,3,3,2
13,U14,4,5,2,2,3,4,5,4,4,...,3,3,4,3,2,4,2,5,4,0
14,U15,2,3,4,4,4,4,2,4,4,...,1,4,2,4,3,4,4,3,4,2

In [ ]:
# data.to_csv('/content/drive/MyDrive/위치/rate_no_clst.csv')

In [ ]:
# 클러스터별로 개체 수 확인
cluster_counts = data['Cluster'].value_counts()
# 클러스터링 결과 출력
print("Cluster Counts:")
print(cluster_counts)

Cluster Counts:
2    7
1    4
0    4
Name: Cluster, dtype: int64

In [ ]:
user_clst_df = data[['U_id', 'Cluster']].sort_values(by='Cluster')
user_clst_df

   U_id  Cluster
3    U4        0
4    U5        0
9   U10        0
13  U14        0
0    U1        1
1    U2        1
2    U3        1
7    U8        1
5    U6        2
6    U7        2
8    U9        2
10  U11        2
11  U12        2
12  U13        2
14  U15        2

## **1. 각 사용자들의 군집(cluster number)을 파일로 저장해야 합니다**

In [ ]:
user_clst_df.to_csv('/content/drive/MyDrive/위치/user_clst.csv')

In [ ]:
user_clst_df

   U_id  Cluster
3    U4        0
4    U5        0
9   U10        0
13  U14        0
0    U1        1
1    U2        1
2    U3        1
7    U8        1
5    U6        2
6    U7        2
8    U9        2
10  U11        2
11  U12        2
12  U13        2
14  U15        2

In [ ]:
data.head(6)

,U_id,P1,P2,P3,P4,P5,P6,P7,P8,P9,...,P20,P21,P22,P23,P24,P25,P26,P27,P28,Cluster
0,U1,4,3,4,2,5,2,3,5,5,...,2,1,2,4,3,4,4,3,4,1
1,U2,3,3,3,3,3,3,3,3,3,...,5,3,3,3,3,3,3,3,3,1
2,U3,4,2,5,4,4,2,1,2,5,...,4,5,2,4,3,3,3,2,4,1
3,U4,3,5,3,2,3,3,3,5,4,...,4,2,3,2,1,2,2,4,2,0
4,U5,3,4,2,2,3,4,3,4,5,...,4,2,3,3,2,2,2,2,2,0
5,U6,3,4,3,3,5,5,4,5,5,...,3,5,3,5,3,5,5,5,5,2

## **2. 평균 구하고 군집별 최댓값 출력**

In [ ]:
avg_df = data.sort_values('Cluster')
avg_df

,U_id,P1,P2,P3,P4,P5,P6,P7,P8,P9,...,P20,P21,P22,P23,P24,P25,P26,P27,P28,Cluster
3,U4,3,5,3,2,3,3,3,5,4,...,4,2,3,2,1,2,2,4,2,0
4,U5,3,4,2,2,3,4,3,4,5,...,4,2,3,3,2,2,2,2,2,0
9,U10,1,3,2,2,4,3,2,2,4,...,4,2,2,2,2,2,2,2,2,0
13,U14,4,5,2,2,3,4,5,4,4,...,3,3,4,3,2,4,2,5,4,0
0,U1,4,3,4,2,5,2,3,5,5,...,2,1,2,4,3,4,4,3,4,1
1,U2,3,3,3,3,3,3,3,3,3,...,5,3,3,3,3,3,3,3,3,1
2,U3,4,2,5,4,4,2,1,2,5,...,4,5,2,4,3,3,3,2,4,1
7,U8,3,3,4,2,4,2,4,2,4,...,3,4,2,4,2,3,2,2,4,1
5,U6,3,4,3,3,5,5,4,5,5,...,3,5,3,5,3,5,5,5,5,2
6,U7,4,4,3,3,4,4,3,4,4,...,5,4,3,3,3,4,4,4,4,2
8,U9,2,5,4,2,4,5,2,4,5,...,5,2,2,4,2,4,3,3,4,2
10,U11,1,2,3,4,4,4,5,4,4,...,3,2,2,3,2,4,4,5,4,2
11,U12,4,4,3,2,4,3,2,2,3,...,3,2,1,4,2,4,5,4,3,2
12,U13,5,3,3,5,5,3,3,5,3,...,5,3,3,2,4,3,2,3,3,2
14,U15,2,3,4,4,4,4,2,4,4,...,1,4,2,4,3,4,4,3,4,2

In [ ]:
# col 생략 없이 출력
pd.set_option('display.max_columns', None)

In [ ]:
avg = avg_df.groupby(['Cluster']) \
            .mean()
            # .max(axis=1)
avg

<ipython-input-16-bf5a7f83552a>:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  .mean()

,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10,P11,P12,P13,P14,P15,P16,P17,P18,P19,P20,P21,P22,P23,P24,P25,P26,P27,P28
Cluster,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,2.75,4.250000,2.250000,2.000000,3.250000,3.50,3.25,3.75,4.25,1.75,3.750000,4.500000,2.500000,1.750000,4.00,3.250000,3.000000,3.000000,2.000000,3.750000,2.250000,3.000000,2.500000,1.750000,2.50,2.000000,3.250000,2.500000
1,3.50,2.750000,4.000000,2.750000,4.000000,2.25,2.75,3.00,4.25,2.75,2.000000,2.500000,2.750000,3.000000,1.75,3.250000,3.000000,2.750000,3.250000,3.500000,3.250000,2.250000,3.750000,2.750000,3.25,3.000000,2.500000,3.750000
2,3.00,3.571429,3.285714,3.285714,4.285714,4.00,3.00,4.00,4.00,3.00,3.857143,4.142857,3.142857,3.142857,4.00,3.714286,3.428571,3.571429,3.142857,3.571429,3.142857,2.285714,3.571429,2.714286,4.00,3.857143,3.857143,3.857143

In [ ]:
# 각 그룹별로 가장 높은 평균과 해당 가게코드 찾기
max_means = avg.max(axis=1)
max_store_codes = avg.idxmax(axis=1)

# 각 그룹별 가장 높은 평균과 해당 가게코드 출력
for cluster, max_mean, max_store_code in zip(max_means.index, max_means, max_store_codes):
    print(f"그룹 {cluster}의 가장 높은 평균: {max_mean}, 가장 높은 평균을 가지는 가게코드: {max_store_code}")

그룹 0의 가장 높은 평균: 4.5, 가장 높은 평균을 가지는 가게코드: P12
그룹 1의 가장 높은 평균: 4.25, 가장 높은 평균을 가지는 가게코드: P9
그룹 2의 가장 높은 평균: 4.285714285714286, 가장 높은 평균을 가지는 가게코드: P5

In [ ]:
max_store_codes[0]

'P12'

In [ ]:
data['Cluster'] == 0

0     False
1     False
2     False
3      True
4      True
5     False
6     False
7     False
8     False
9      True
10    False
11    False
12    False
13     True
14    False
Name: Cluster, dtype: bool

In [ ]:
data

,U_id,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10,P11,P12,P13,P14,P15,P16,P17,P18,P19,P20,P21,P22,P23,P24,P25,P26,P27,P28,Cluster
0,U1,4,3,4,2,5,2,3,5,5,3,3,3,3,2,1,2,4,4,2,2,1,2,4,3,4,4,3,4,1
1,U2,3,3,3,3,3,3,3,3,3,3,2,2,2,2,2,3,3,2,3,5,3,3,3,3,3,3,3,3,1
2,U3,4,2,5,4,4,2,1,2,5,1,1,3,2,4,2,5,2,2,4,4,5,2,4,3,3,3,2,4,1
3,U4,3,5,3,2,3,3,3,5,4,1,4,5,4,2,4,2,3,3,2,4,2,3,2,1,2,2,4,2,0
4,U5,3,4,2,2,3,4,3,4,5,2,4,5,3,2,3,4,4,4,2,4,2,3,3,2,2,2,2,2,0
5,U6,3,4,3,3,5,5,4,5,5,3,5,5,3,3,5,5,4,4,4,3,5,3,5,3,5,5,5,5,2
6,U7,4,4,3,3,4,4,3,4,4,3,4,5,4,5,4,4,4,3,4,5,4,3,3,3,4,4,4,4,2
7,U8,3,3,4,2,4,2,4,2,4,4,2,2,4,4,2,3,3,3,4,3,4,2,4,2,3,2,2,4,1
8,U9,2,5,4,2,4,5,2,4,5,3,3,4,4,5,3,4,4,5,3,5,2,2,4,2,4,3,3,4,2
9,U10,1,3,2,2,4,3,2,2,4,2,4,4,2,2,4,3,2,2,2,4,2,2,2,2,2,2,2,2,0
10,U11,1,2,3,4,4,4,5,4,4,2,3,3,4,3,5,2,3,3,3,3,2,2,3,2,4,4,5,4,2
11,U12,4,4,3,2,4,3,2,2,3,2,4,4,2,2,4,3,2,2,3,3,2,1,4,2,4,5,4,3,2
12,U13,5,3,3,5,5,3,3,5,3,4,4,4,2,2,3,3,3,4,2,5,3,3,2,4,3,2,3,3,2
13,U14,4,5,2,2,3,4,5,4,4,2,3,4,1,1,5,4,3,3,2,3,3,4,3,2,4,2,5,4,0
14,U15,2,3,4,4,4,4,2,4,4,4,4,4,3,2,4,5,4,4,3,1,4,2,4,3,4,4,3,4,2

In [ ]:
data.iloc[1]['Cluster']

1

## **3. 기존 15명 대상으로 장소 추천**

In [ ]:
for i in range(len(data)):
  if data.iloc[i]['Cluster'] == 0:
    print(data.iloc[i]['U_id'], '님의 추천 카페: ', max_store_codes[0])
  elif data.iloc[i]['Cluster'] == 1:
    print(data.iloc[i]['U_id'], '님의 추천 카페: ', max_store_codes[1])
  else:
    print(data.iloc[i]['U_id'], '님의 추천 카페: ', max_store_codes[2])

U1 님의 추천 카페:  P9
U2 님의 추천 카페:  P9
U3 님의 추천 카페:  P9
U4 님의 추천 카페:  P12
U5 님의 추천 카페:  P12
U6 님의 추천 카페:  P5
U7 님의 추천 카페:  P5
U8 님의 추천 카페:  P9
U9 님의 추천 카페:  P5
U10 님의 추천 카페:  P12
U11 님의 추천 카페:  P5
U12 님의 추천 카페:  P5
U13 님의 추천 카페:  P5
U14 님의 추천 카페:  P12
U15 님의 추천 카페:  P5

## **4. 새 사용자 들어왔을 때, 최댓값의 가게 추천**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# 새 사용자의 데이터 받기
new_user = pd.read_excel('/content/drive/MyDrive/위치/새 사용자.xlsx')
# new_user
new_user_co = new_user.drop('U_id', axis=1)  # 새 사용자의 유저 아이디 없앰.
new_user_co

,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10,P11,P12,P13,P14,P15,P16,P17,P18,P19,P20,P21,P22,P23,P24,P25,P26,P27,P28
0,5,3,4,4,4,4,2,4,1,1,4,4,3,2,4,2,4,4,3,1,4,5,4,3,4,4,1,4

In [ ]:
print(len(new_data))
print(len(new_user_co))

15
1

In [ ]:
# 기존 데이터와 새 사용자의 df 합침
result1 = pd.concat([new_data, new_user_co])
result1

,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10,P11,P12,P13,P14,P15,P16,P17,P18,P19,P20,P21,P22,P23,P24,P25,P26,P27,P28
0,4,3,4,2,5,2,3,5,5,3,3,3,3,2,1,2,4,4,2,2,1,2,4,3,4,4,3,4
1,3,3,3,3,3,3,3,3,3,3,2,2,2,2,2,3,3,2,3,5,3,3,3,3,3,3,3,3
2,4,2,5,4,4,2,1,2,5,1,1,3,2,4,2,5,2,2,4,4,5,2,4,3,3,3,2,4
3,3,5,3,2,3,3,3,5,4,1,4,5,4,2,4,2,3,3,2,4,2,3,2,1,2,2,4,2
4,3,4,2,2,3,4,3,4,5,2,4,5,3,2,3,4,4,4,2,4,2,3,3,2,2,2,2,2
5,3,4,3,3,5,5,4,5,5,3,5,5,3,3,5,5,4,4,4,3,5,3,5,3,5,5,5,5
6,4,4,3,3,4,4,3,4,4,3,4,5,4,5,4,4,4,3,4,5,4,3,3,3,4,4,4,4
7,3,3,4,2,4,2,4,2,4,4,2,2,4,4,2,3,3,3,4,3,4,2,4,2,3,2,2,4
8,2,5,4,2,4,5,2,4,5,3,3,4,4,5,3,4,4,5,3,5,2,2,4,2,4,3,3,4
9,1,3,2,2,4,3,2,2,4,2,4,4,2,2,4,3,2,2,2,4,2,2,2,2,2,2,2,2
10,1,2,3,4,4,4,5,4,4,2,3,3,4,3,5,2,3,3,3,3,2,2,3,2,4,4,5,4
11,4,4,3,2,4,3,2,2,3,2,4,4,2,2,4,3,2,2,3,3,2,1,4,2,4,5,4,3
12,5,3,3,5,5,3,3,5,3,4,4,4,2,2,3,3,3,4,2,5,3,3,2,4,3,2,3,3
13,4,5,2,2,3,4,5,4,4,2,3,4,1,1,5,4,3,3,2,3,3,4,3,2,4,2,5,4
14,2,3,4,4,4,4,2,4,4,4,4,4,3,2,4,5,4,4,3,1,4,2,4,3,4,4,3,4
0,5,3,4,4,4,4,2,4,1,1,4,4,3,2,4,2,4,4,3,1,4,5,4,3,4,4,1,4

In [ ]:
# kmeans 적용
kmeans = KMeans(n_clusters=3, random_state=42)
clusters = kmeans.fit_predict(result1)

# 클러스터링 결과를 DataFrame에 추가
result1['Cluster'] = clusters
result1

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10,P11,P12,P13,P14,P15,P16,P17,P18,P19,P20,P21,P22,P23,P24,P25,P26,P27,P28,Cluster
0,4,3,4,2,5,2,3,5,5,3,3,3,3,2,1,2,4,4,2,2,1,2,4,3,4,4,3,4,2
1,3,3,3,3,3,3,3,3,3,3,2,2,2,2,2,3,3,2,3,5,3,3,3,3,3,3,3,3,2
2,4,2,5,4,4,2,1,2,5,1,1,3,2,4,2,5,2,2,4,4,5,2,4,3,3,3,2,4,0
3,3,5,3,2,3,3,3,5,4,1,4,5,4,2,4,2,3,3,2,4,2,3,2,1,2,2,4,2,2
4,3,4,2,2,3,4,3,4,5,2,4,5,3,2,3,4,4,4,2,4,2,3,3,2,2,2,2,2,2
5,3,4,3,3,5,5,4,5,5,3,5,5,3,3,5,5,4,4,4,3,5,3,5,3,5,5,5,5,1
6,4,4,3,3,4,4,3,4,4,3,4,5,4,5,4,4,4,3,4,5,4,3,3,3,4,4,4,4,1
7,3,3,4,2,4,2,4,2,4,4,2,2,4,4,2,3,3,3,4,3,4,2,4,2,3,2,2,4,0
8,2,5,4,2,4,5,2,4,5,3,3,4,4,5,3,4,4,5,3,5,2,2,4,2,4,3,3,4,1
9,1,3,2,2,4,3,2,2,4,2,4,4,2,2,4,3,2,2,2,4,2,2,2,2,2,2,2,2,2
10,1,2,3,4,4,4,5,4,4,2,3,3,4,3,5,2,3,3,3,3,2,2,3,2,4,4,5,4,1
11,4,4,3,2,4,3,2,2,3,2,4,4,2,2,4,3,2,2,3,3,2,1,4,2,4,5,4,3,2
12,5,3,3,5,5,3,3,5,3,4,4,4,2,2,3,3,3,4,2,5,3,3,2,4,3,2,3,3,2
13,4,5,2,2,3,4,5,4,4,2,3,4,1,1,5,4,3,3,2,3,3,4,3,2,4,2,5,4,2
14,2,3,4,4,4,4,2,4,4,4,4,4,3,2,4,5,4,4,3,1,4,2,4,3,4,4,3,4,1
0,5,3,4,4,4,4,2,4,1,1,4,4,3,2,4,2,4,4,3,1,4,5,4,3,4,4,1,4,2

In [ ]:
new_users_clust = result1.iloc[-1,:]['Cluster']
new_users_clust  # Cluster 2

# new_user['Cluster'] = new_users_clust
# new_user

2

In [ ]:
new_user_avg_df = result1.sort_values('Cluster')
new_user_avg_df

,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10,P11,P12,P13,P14,P15,P16,P17,P18,P19,P20,P21,P22,P23,P24,P25,P26,P27,P28,Cluster
2,4,2,5,4,4,2,1,2,5,1,1,3,2,4,2,5,2,2,4,4,5,2,4,3,3,3,2,4,0
7,3,3,4,2,4,2,4,2,4,4,2,2,4,4,2,3,3,3,4,3,4,2,4,2,3,2,2,4,0
5,3,4,3,3,5,5,4,5,5,3,5,5,3,3,5,5,4,4,4,3,5,3,5,3,5,5,5,5,1
6,4,4,3,3,4,4,3,4,4,3,4,5,4,5,4,4,4,3,4,5,4,3,3,3,4,4,4,4,1
8,2,5,4,2,4,5,2,4,5,3,3,4,4,5,3,4,4,5,3,5,2,2,4,2,4,3,3,4,1
10,1,2,3,4,4,4,5,4,4,2,3,3,4,3,5,2,3,3,3,3,2,2,3,2,4,4,5,4,1
14,2,3,4,4,4,4,2,4,4,4,4,4,3,2,4,5,4,4,3,1,4,2,4,3,4,4,3,4,1
0,4,3,4,2,5,2,3,5,5,3,3,3,3,2,1,2,4,4,2,2,1,2,4,3,4,4,3,4,2
1,3,3,3,3,3,3,3,3,3,3,2,2,2,2,2,3,3,2,3,5,3,3,3,3,3,3,3,3,2
3,3,5,3,2,3,3,3,5,4,1,4,5,4,2,4,2,3,3,2,4,2,3,2,1,2,2,4,2,2
4,3,4,2,2,3,4,3,4,5,2,4,5,3,2,3,4,4,4,2,4,2,3,3,2,2,2,2,2,2
9,1,3,2,2,4,3,2,2,4,2,4,4,2,2,4,3,2,2,2,4,2,2,2,2,2,2,2,2,2
11,4,4,3,2,4,3,2,2,3,2,4,4,2,2,4,3,2,2,3,3,2,1,4,2,4,5,4,3,2
12,5,3,3,5,5,3,3,5,3,4,4,4,2,2,3,3,3,4,2,5,3,3,2,4,3,2,3,3,2
13,4,5,2,2,3,4,5,4,4,2,3,4,1,1,5,4,3,3,2,3,3,4,3,2,4,2,5,4,2
0,5,3,4,4,4,4,2,4,1,1,4,4,3,2,4,2,4,4,3,1,4,5,4,3,4,4,1,4,2

In [ ]:
new_user_avg = new_user_avg_df.groupby(['Cluster']) \
                              .mean()
            # .max(axis=1)
new_user_avg

,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10,P11,P12,P13,P14,P15,P16,P17,P18,P19,P20,P21,P22,P23,P24,P25,P26,P27,P28
Cluster,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,3.500000,2.500000,4.500000,3.000000,4.000000,2.000000,2.500000,2.000000,4.500000,2.500000,1.500000,2.500000,3.000000,4.000000,2.000000,4.000000,2.500000,2.500000,4.000000,3.500000,4.500000,2.000000,4.0,2.500000,3.000000,2.500000,2.0,4.0
1,2.400000,3.600000,3.400000,3.200000,4.200000,4.400000,3.200000,4.200000,4.400000,3.000000,3.800000,4.200000,3.600000,3.600000,4.200000,4.000000,3.800000,3.800000,3.400000,3.400000,3.400000,2.400000,3.8,2.600000,4.200000,4.000000,4.0,4.2
2,3.555556,3.666667,2.888889,2.666667,3.777778,3.222222,2.888889,3.777778,3.555556,2.222222,3.555556,3.888889,2.444444,1.888889,3.333333,2.888889,3.111111,3.111111,2.333333,3.444444,2.444444,2.888889,3.0,2.444444,3.111111,2.888889,3.0,3.0

In [ ]:
# 각 그룹별로 가장 높은 평균과 해당 가게코드 찾기
new_user_max_means = new_user_avg.max(axis=1)

new_user_max_store_codes = []
for index, row in new_user_avg.iterrows():
    max_value = row.max()
    max_columns = row.index[row == max_value].tolist()
    new_user_max_store_codes.append(max_columns)

# 각 그룹별 가장 높은 평균과 해당 가게코드 출력
for cluster, new_user_max_mean, new_user_max_store_code in zip(new_user_max_means.index, new_user_max_means, new_user_max_store_codes):
    print(f"그룹 {cluster}의 가장 높은 평균: {new_user_max_mean}, 가장 높은 평균을 가지는 가게코드: {new_user_max_store_code}")

그룹 0의 가장 높은 평균: 4.5, 가장 높은 평균을 가지는 가게코드: ['P3', 'P9', 'P21']
그룹 1의 가장 높은 평균: 4.4, 가장 높은 평균을 가지는 가게코드: ['P6', 'P9']
그룹 2의 가장 높은 평균: 3.888888888888889, 가장 높은 평균을 가지는 가게코드: ['P12']

In [ ]:
# new_user_max_store_codes[0]

In [ ]:
for i in range(0, 3):
  if new_users_clust == [i]:
    print('새 사용자에게 추천하는 가게: ', new_user_max_store_codes[i])

새 사용자에게 추천하는 가게:  ['P12']